all:
	g++ -D VERBOSE -std=c++11 -o allcalls overhead.cpp

task02:
	g++ -D TASK02 -std=c++11 -o overhead overhead.cpp
task03:
	g++ -D TASK03 -std=c++11 -o casting overhead.cpp

clean:
	rm allcalls overhead casting
